#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find /media/D/prog/cs /media/D/prog/react-native  ~/study -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

new_session() {
	tmux new-session -d -s $selected_name -c $selected -n "General"
        tmux send-keys -t $selected_name "ready-tmux" ^M
}

#For reference check the Freeform scheme of the logic
if [[ -z $tmux_running ]] then
	new_session
	tmux attach-session -t $selected_name
else
	if ! tmux has-session -t $selected_name 2> /dev/null; then
		new_session
	fi
	
	if [[ -z $TMUX ]] then
		tmux attach-session -t $selected_name
	else 
		tmux switch-client -t $selected_name
	fi
fi

